export const archiveRoot = "C:\\Users\\cjten\\Desktop\\Project Showcase_Master";
export const organizedRoot = "C:\\Users\\cjten\\Desktop\\Project Showcase_Organized";

const project = (definition) => ({
  confidence: "confirmed",
  status: "Archive",
  featured: false,
  publish: false,
  repositories: [],
  tags: [],
  specs: [],
  challenges: [],
  results: [],
  future: [],
  ...definition,
});

export const projects = [
  project({
    slug: "2d-drawing-plotter",
    title: "CNC 2D Drawing Plotter",
    category: "Robotics",
    industry: "Digital fabrication",
    discipline: "Motion control and mechatronics",
    purpose: "A pen-plotter mechanism that converts digital paths into repeatable two-axis drawings.",
    technologies: ["Stepper motors", "Motion control", "Mechanical design", "CNC concepts"],
    sourceFolder: "2d drawing",
    tags: ["Plotter", "Motion Control", "CNC", "Mechatronics"],
    challenges: ["Coordinating two-axis motion", "Maintaining pen pressure and line quality"],
    results: ["Produced detailed physical drawings from controlled motion paths"],
    future: ["Add vector-file import and closed-loop position feedback"],
  }),
  project({
    slug: "2d-slam-mobile-robot",
    title: "2D SLAM Mobile Robot",
    category: "Robotics",
    industry: "Autonomous systems",
    discipline: "Mapping and localization",
    purpose: "A mobile robot demonstration for real-time mapping, navigation visualization, and SLAM experimentation.",
    technologies: ["2D SLAM", "Mobile robotics", "LiDAR", "Robot visualization"],
    sourceFolder: "2DSLAM_Robot",
    tags: ["SLAM", "LiDAR", "Robotics", "Mapping"],
    specs: ["Two recorded demonstrations", "Tablet-based mapping visualization"],
    challenges: ["Stable scan alignment", "Mapping while the platform is moving"],
    results: ["Captured a working robot and live mapping workflow"],
    future: ["Publish sensor calibration, map quality, and benchmark details"],
    repositories: ["https://github.com/Chathunka/ros2_cartographer"],
    coverSource: "2DSLAM_Robot/final4k-Cover.jpg",
    publish: true,
    featured: true,
  }),
  project({
    slug: "additive-manufacturing-prototypes",
    title: "Additive Manufacturing and CAD Prototypes",
    category: "Research and Experimental Projects",
    industry: "Product prototyping",
    discipline: "CAD and digital fabrication",
    purpose: "A collection of functional 3D-printed prototypes including aircraft models, robotic hand parts, instrument frames, and mechanical fixtures.",
    technologies: ["3D printing", "CAD", "Rapid prototyping", "Mechanical design"],
    sourceFolder: "3d Printing",
    tags: ["3D Printing", "CAD", "Prototyping", "Mechanical Design"],
    results: ["Produced functional and presentation-grade parts across multiple design iterations"],
    future: ["Publish source CAD, print settings, and material comparisons"],
    coverSource: "3d Printing/Published/3dprinting.jpg",
    publish: true,
  }),
  project({
    slug: "beer-keg-telemetry-rtu",
    title: "Beer Keg Telemetry Data Logger and RTU",
    category: "IoT",
    industry: "Beverage dispensing",
    discipline: "Industrial telemetry and embedded electronics",
    purpose: "A modular Wi-Fi/3G remote terminal that monitors beer flow, keg pressure, cooler and tap temperatures, and compressor power while supporting remote control.",
    technologies: ["GSM/GPRS", "Wi-Fi", "HTTP", "MQTT", "Azure IoT", "Analog sensing", "Pulse inputs"],
    sourceFolder: "Beer Keg",
    tags: ["IIoT", "Telemetry", "MQTT", "GSM", "Remote Monitoring"],
    specs: ["Four pressure channels", "Five temperature channels", "Four flow-meter inputs", "Two relay outputs", "Battery backup"],
    challenges: ["Reliable field telemetry", "Offline buffering", "Mixed analog, pulse, and relay interfaces"],
    results: ["Completed enclosure, electronics, sensor harness, user manual, and system flow documentation"],
    future: ["Modernize the gateway security model and cloud device management"],
    coverSource: "Beer Keg/IMG_20170209_050227.jpg",
    publish: true,
    featured: true,
  }),
  project({
    slug: "biogas-experimental-system",
    title: "Biogas Production and Burner Experiment",
    category: "Research and Experimental Projects",
    industry: "Renewable energy",
    discipline: "Energy systems prototyping",
    purpose: "An experimental biogas setup documenting gas production hardware and a burner demonstration.",
    technologies: ["Biogas", "Combustion", "Mechanical prototyping", "Energy systems"],
    sourceFolder: "bio gas",
    tags: ["Biogas", "Renewable Energy", "Prototype"],
    challenges: ["Gas containment and safe burner operation"],
    results: ["Recorded a functioning experimental setup and flame demonstration"],
    future: ["Add pressure sensing, gas composition measurement, and safety interlocks"],
  }),
  project({
    slug: "device-condition-monitoring-dashboard",
    title: "Device Condition Monitoring Dashboard",
    category: "Software Development",
    industry: "Industrial monitoring",
    discipline: "Operational dashboards",
    purpose: "A dashboard presentation showing live operational gauges and condition indicators.",
    technologies: ["Dashboard UI", "Telemetry visualization", "Condition monitoring"],
    sourceFolder: "DCM",
    tags: ["Dashboard", "Monitoring", "Telemetry"],
    confidence: "inferred - confirm DCM expansion",
    results: ["Documented an operational dashboard presentation"],
    future: ["Confirm system scope and connect the dashboard to its source project documentation"],
  }),
  project({
    slug: "dangerous-gas-monitoring",
    title: "Industrial Dangerous Gas Monitoring System",
    category: "IoT",
    industry: "Port and industrial safety",
    discipline: "Industrial IoT and safety monitoring",
    purpose: "A container-port monitoring solution for dangerous gases using field sensors, an industrial gateway, dashboards, alarms, and notifications.",
    technologies: ["Modbus", "Industrial gas sensors", "IIoT gateway", "AWS", "MERN", "Alerts"],
    sourceFolder: "DGM",
    tags: ["Industrial Safety", "Gas Monitoring", "Modbus", "AWS", "IIoT"],
    specs: ["Supports gases including CO, H2S, Cl2, and CH4", "Cloud visualization and alarms"],
    challenges: ["Industrial communications", "Reliable alarm delivery", "Field deployment"],
    results: ["Deployed monitoring hardware and operational visualization in a port environment"],
    future: ["Add predictive sensor maintenance and edge anomaly detection"],
    repositories: [
      "https://github.com/Chathunka/O2-Sensor_ModBus_Read",
      "https://github.com/Chathunka/ESP32_ModBus_MAX485_Serial",
    ],
    coverSource: "DGM/20231219_142249.jpg",
    publish: true,
    featured: true,
  }),
  project({
    slug: "digital-queue-display",
    title: "Digital Queue Display System",
    category: "Electronics",
    industry: "Customer service and queue management",
    discipline: "Display electronics and embedded control",
    purpose: "A custom current-number and queue-length display with dot-matrix messaging and large seven-segment indicators.",
    technologies: ["LED matrix", "Seven-segment display", "Embedded control", "Custom wiring"],
    sourceFolder: "Digital Displays",
    tags: ["LED Display", "Queue System", "Electronics", "Embedded"],
    challenges: ["Driving multiple display types", "Readable enclosure and layout design"],
    results: ["Built and tested complete queue displays from prototype wiring to finished enclosure"],
    future: ["Add network-based ticket updates and a browser administration interface"],
    coverSource: "Digital Displays/IMG_20181028_232236.jpg",
    publish: true,
  }),
  project({
    slug: "operator-fatigue-management",
    title: "Operator Fatigue Management Installation",
    category: "Automotive Systems",
    industry: "Heavy equipment and industrial vehicles",
    discipline: "Vehicle safety systems",
    purpose: "An installed fatigue-management device for an industrial vehicle operator station.",
    technologies: ["Vehicle electronics", "Operator monitoring", "Safety system integration"],
    sourceFolder: "Fatigue Management",
    tags: ["Fatigue Monitoring", "Vehicle Safety", "Installation"],
    confidence: "asset evidence - detailed system specification unavailable",
    results: ["Documented installation within a heavy-equipment cab"],
    future: ["Document sensing method, alert logic, vehicle interface, and validation results"],
    coverSource: "Fatigue Management/20231128_124143.jpg",
    publish: true,
  }),
  project({
    slug: "fingerprint-access-terminal",
    title: "Fingerprint and Keypad Access Terminal",
    category: "Embedded Systems",
    industry: "Access control",
    discipline: "Biometric embedded systems",
    purpose: "A compact fingerprint and keypad terminal intended for identity, attendance, or controlled-entry workflows.",
    technologies: ["Fingerprint sensor", "Keypad", "Embedded controller", "Access control"],
    sourceFolder: "Finger Print",
    tags: ["Biometrics", "Fingerprint", "Access Control", "Embedded"],
    results: ["Completed a packaged biometric terminal prototype"],
    future: ["Add audit logging, network enrollment, and encrypted credential storage"],
    coverSource: "Finger Print/IMG_20180826_221349.jpg",
    publish: true,
  }),
  project({
    slug: "four-channel-humidifier-controller",
    title: "Four-Channel Humidifier Controller",
    category: "Embedded Systems",
    industry: "Environmental control",
    discipline: "Firmware and PCB design",
    purpose: "An ATmega328P-based controller for independently driving four mist-maker channels.",
    technologies: ["ATmega328P", "Arduino", "PCB design", "Relay control", "Power electronics"],
    sourceFolder: "Humidifier",
    tags: ["ATmega328P", "Arduino", "PCB", "Humidifier"],
    specs: ["Four controlled channels", "Custom PCB", "Discrete output stages"],
    challenges: ["Power switching", "PCB layout", "Multi-channel control"],
    results: ["Designed, fabricated, assembled, and demonstrated the controller hardware"],
    future: ["Add humidity feedback, current monitoring, and enclosure thermal validation"],
    repositories: ["https://github.com/Chathunka/Arduino-Humidifier"],
    coverSource: "Humidifier/20230116_082458.jpg",
    publish: true,
    featured: true,
  }),
  project({
    slug: "laser-cutting-fabrication",
    title: "Laser Cutting and Engraving Prototypes",
    category: "Research and Experimental Projects",
    industry: "Digital fabrication",
    discipline: "Manufacturing and product prototyping",
    purpose: "A set of laser-cut and engraved parts used to validate lettering, decorative patterns, and fabrication workflows.",
    technologies: ["Laser cutting", "Laser engraving", "CAD", "Fabrication"],
    sourceFolder: "laser cutting",
    tags: ["Laser Cutting", "Fabrication", "CAD"],
    results: ["Produced engraved lettering and decorative cut panels"],
    future: ["Publish material, power, speed, and kerf calibration tables"],
  }),
  project({
    slug: "modbus-oxygen-sensor-reader",
    title: "Modbus Oxygen Sensor Reader",
    category: "Embedded Systems",
    industry: "Environmental monitoring",
    discipline: "Industrial communications",
    purpose: "A hardware and software test setup for reading oxygen sensor measurements over Modbus/RS485.",
    technologies: ["Modbus RTU", "RS485", "MAX485", "ESP32", "O2 sensor"],
    sourceFolder: "ModBusReader",
    tags: ["Modbus", "RS485", "ESP32", "Oxygen Sensor"],
    challenges: ["Register interpretation", "Serial timing", "Reliable field wiring"],
    results: ["Demonstrated live oxygen readings through multiple test configurations"],
    future: ["Package as a reusable diagnostics tool with register profiles and logging"],
    repositories: [
      "https://github.com/Chathunka/O2-Sensor_ModBus_Read",
      "https://github.com/Chathunka/ESP32_ModBus_MAX485_Serial",
    ],
  }),
  project({
    slug: "opengl-virtual-room",
    title: "OpenGL Virtual Room Simulation",
    category: "Software Development",
    industry: "Computer graphics",
    discipline: "3D rendering and simulation",
    purpose: "A rendered virtual room featuring textured objects, transparent glass, multiple reflections, dynamic lighting, shadows, and free-camera navigation.",
    technologies: ["OpenGL", "C++", "GLFW", "GLEW", "Texture mapping", "Stencil reflections"],
    sourceFolder: "Open GL",
    tags: ["OpenGL", "Computer Graphics", "3D Simulation", "C++"],
    specs: ["Free and static cameras", "Textured compound objects", "Planar mirrors", "Dynamic shadows"],
    challenges: ["Multiple reflections", "Transparency", "Combining shadows with stencil rendering"],
    results: ["Delivered an executable scene and a six-page technical report"],
    future: ["Port to modern OpenGL shaders and a portable build system"],
  }),
  project({
    slug: "et-robocon-entry-robot",
    title: "ET Robocon Entry Robot Control System",
    category: "Robotics",
    industry: "Robotics competition",
    discipline: "Autonomous control software",
    purpose: "A LEGO EV3 competition controller combining PID line tracing, color-based decisions, precision turning, object carrying, and distance measurement.",
    technologies: ["LEGO EV3", "PID control", "Line following", "Color sensing", "Distance sensing"],
    sourceFiles: ["Best_Time_ETRobo_ent_WDCJTennakoon.mp4", "Other/ENTRY RUNNING SYSTEM_WDCJ_Tennakoon_afl020105.pdf"],
    tags: ["ET Robocon", "PID", "Line Tracing", "EV3"],
    specs: ["Single color sensor", "PID turn-power calculation", "Bonus-area object carrying"],
    challenges: ["Fast line tracing", "Accurate 90-degree turns", "Optimal object placement"],
    results: ["Completed the simulated entry course with documented V-model design artifacts"],
    future: ["Publish controller source and formal tuning data"],
  }),
  project({
    slug: "student-management-system",
    title: "Aircraft Training Student Management System",
    category: "Software Development",
    industry: "Aviation training",
    discipline: "Database application development",
    purpose: "A Microsoft Access system for student records, course modules, practical-hour attendance, search, and exam eligibility.",
    technologies: ["Microsoft Access", "Relational database", "Forms", "Reporting"],
    sourceFiles: ["Other/SLAC STT Student Management System_07_09_2017.pdf"],
    tags: ["Database", "Aviation Training", "Attendance", "Microsoft Access"],
    specs: ["Student records", "Course and practical modules", "Attendance calculation", "Eligibility reporting"],
    results: ["Documented a complete operational workflow across ten pages"],
    future: ["Migrate to a secure web application with role-based access and audit history"],
  }),
  project({
    slug: "rapid-prototyping-artifacts",
    title: "Rapid Prototyping and Custom Control Artifacts",
    category: "Research and Experimental Projects",
    industry: "Product development",
    discipline: "Mechanical and electronics prototyping",
    purpose: "A collection of 3D-printed mechanisms, engraved objects, compact enclosures, and custom controller PCBs.",
    technologies: ["3D printing", "PCB assembly", "Mechanical prototyping", "Enclosure design"],
    sourceFiles: [
      "Other/20211103_100520.jpg", "Other/20211103_100541.jpg", "Other/20211103_100551.jpg",
      "Other/20211103_100601.jpg", "Other/20211103_100607.jpg", "Other/20211103_100634.jpg",
      "Other/20211103_100904.mp4", "Other/20211119_103016.jpg", "Other/20211119_103034.jpg",
      "Other/20221123_110304.jpg", "Other/20221123_110332.jpg", "Other/20221123_110354.jpg",
    ],
    tags: ["Rapid Prototyping", "PCB", "3D Printing"],
    results: ["Preserved multiple physical proof-of-concept iterations"],
    future: ["Separate each artifact into a documented mini-project with design files"],
  }),
  project({
    slug: "compact-environmental-chamber",
    title: "Compact Environmental Chamber Prototype",
    category: "IoT",
    industry: "Environmental control",
    discipline: "Embedded monitoring prototype",
    purpose: "A compact enclosure prototype demonstrated with local display and controlled internal conditions.",
    technologies: ["Embedded control", "Display", "Environmental chamber", "Prototype enclosure"],
    sourceFiles: [
      "Other/20201019_093911.mp4",
      "Other/20201112_163122.mp4", "Other/20201112_164020.mp4", "Other/20201112_164406.mp4",
    ],
    tags: ["Environmental Control", "Prototype", "Embedded"],
    confidence: "asset evidence - detailed specification unavailable",
    results: ["Recorded the sensing electronics and packaged chamber prototype"],
    future: ["Document sensors, control loop, operating range, and test results"],
  }),
  project({
    slug: "humanoid-robot-demonstration",
    title: "Humanoid Robot Motion Demonstration",
    category: "Robotics",
    industry: "Educational robotics",
    discipline: "Robot motion and actuation",
    purpose: "A small humanoid robot demonstration showing coordinated walking and body motion.",
    technologies: ["Humanoid robotics", "Servo control", "Motion sequencing"],
    sourceFiles: ["Other/20220120_153043.mp4", "Other/20220120_154056.mp4"],
    tags: ["Humanoid Robot", "Servo", "Motion Control"],
    results: ["Captured repeatable walking and movement demonstrations"],
    future: ["Document servo layout, gait sequence, controller, and balance strategy"],
  }),
  project({
    slug: "pure-sine-wave-inverter",
    title: "Pure Sine Wave Inverter Controller",
    category: "Electronics",
    industry: "Power conversion",
    discipline: "Power electronics and embedded control",
    purpose: "A custom control and switching board for generating a pure sine wave inverter output.",
    technologies: ["Power electronics", "Microcontroller", "MOSFET switching", "PCB design", "Inverter"],
    sourceFolder: "Pure Sine Wave Inverter",
    tags: ["Inverter", "Power Electronics", "PCB", "Embedded"],
    challenges: ["Switch timing", "Power-stage isolation", "Thermal management"],
    results: ["Fabricated controller and switching-stage prototype boards"],
    future: ["Document output power, waveform THD, protection, and efficiency"],
    coverSource: "Pure Sine Wave Inverter/20221212_152803.jpg",
    publish: true,
  }),
  project({
    slug: "er-diagram-digitizer",
    title: "Hand-Drawn ER Diagram Digitizer",
    category: "AI & Machine Learning",
    industry: "Developer tools and education",
    discipline: "Computer vision and document understanding",
    purpose: "A Python/OpenCV pipeline that converts photographed hand-drawn entity-relationship diagrams into structured relationships and SQL-oriented output.",
    technologies: ["Python", "OpenCV", "Grayscale processing", "Denoising", "Contour detection", "Shape classification"],
    sourceFolder: "Python Image processing",
    additionalSources: ["Image Processing and Object detection, 3D simulation.docx"],
    tags: ["Computer Vision", "OpenCV", "ER Diagram", "Python"],
    specs: ["Shape classification", "Relationship extraction", "SQL statement generation"],
    challenges: ["Noisy camera images", "Hand-drawn shape variation", "Relationship interpretation"],
    results: ["Produced a working research prototype and retained source code"],
    future: ["Add OCR, graph validation, and modern deep-learning-based symbol detection"],
    coverSource: "Python Image processing/images/15.jpg",
    publish: true,
    featured: true,
  }),
  project({
    slug: "rfid-inventory-terminal",
    title: "RFID Inventory and Swipe Reader Terminal",
    category: "IoT",
    industry: "Inventory and identification",
    discipline: "Embedded identification systems",
    purpose: "A packaged RFID reader terminal with display, wireless connectivity, and card/key-fob interaction.",
    technologies: ["RDM6300", "RFID", "ESP32", "Arduino", "LCD", "Wi-Fi"],
    sourceFolder: "RFID reader",
    tags: ["RFID", "Inventory", "ESP32", "Access Control"],
    results: ["Built and demonstrated a self-contained RFID terminal"],
    future: ["Add encrypted APIs, offline transaction queues, and administrative enrollment"],
    repositories: [
      "https://github.com/Chathunka/RDM6300_RFID_Swipe_Reader-Arduino",
      "https://github.com/Chathunka/RDM6300_RFID_Swipe_Reader-ESP32",
      "https://github.com/Chathunka/Inventory-Management-RFID",
    ],
    coverSource: "RFID reader/20240215_093858.jpg",
    publish: true,
  }),
  project({
    slug: "smart-cooler-logger",
    title: "GSM Smart Cooler Data Logger and Protection Unit",
    category: "IoT",
    industry: "Cold-chain and equipment monitoring",
    discipline: "Embedded telemetry and condition monitoring",
    purpose: "A cooler monitoring unit that measures temperature, vibration, noise, orientation, voltage, and current, reports through GSM/USB, and can protect the compressor during critical conditions.",
    technologies: ["GSM/GPRS", "USB", "HTTP", "MQTT", "IMU", "Temperature sensing", "Power monitoring", "Relay control"],
    sourceFolder: "Smart Cooler",
    tags: ["Cold Chain", "GSM", "Condition Monitoring", "IoT"],
    specs: ["10-bit analog inputs", "IMU sensing", "230 V / 10 A relay output", "PC configuration software", "Cloud reporting"],
    challenges: ["Multi-sensor integration", "Condition inference", "Safe compressor switching"],
    results: ["Completed electronics, enclosure, sensor unit, PC utility, demonstration, and user documentation"],
    future: ["Add predictive maintenance models and modern device provisioning"],
    coverSource: "Smart Cooler/Published/Smart Cooler.jpg",
    publish: true,
    featured: true,
  }),
  project({
    slug: "automatic-tennis-ball-shooter",
    title: "Automatic Tennis Ball Training Machine",
    category: "Robotics",
    industry: "Sports technology",
    discipline: "Mechatronics and motion systems",
    purpose: "A portable tennis training machine with controllable launch speed, angle, spin, automatic feeding, and premium random-target capability.",
    technologies: ["DC motors", "Motor speed control", "Automatic feeder", "Battery power", "RF remote", "Mechatronics"],
    sourceFolder: "TennisBallShooter",
    tags: ["Sports Engineering", "Mechatronics", "Motor Control", "Automation"],
    specs: ["Speed and spin control", "Automatic feeder", "Vertical and horizontal targeting", "12 V battery operation"],
    challenges: ["Consistent ball feed", "Repeatable launch speed", "Angle adjustment"],
    results: ["Built and demonstrated the mechanical launcher and feeder prototype"],
    future: ["Add vision-based target selection, closed-loop wheel speed, and safety guarding"],
    coverSource: "TennisBallShooter/IMG_20181203_214756.jpg",
    publish: true,
    featured: true,
  }),
  project({
    slug: "vending-machine-controller",
    title: "USB-Configurable Vending Machine Controller",
    category: "Embedded Systems",
    industry: "Retail automation",
    discipline: "Embedded motor control and desktop utilities",
    purpose: "A packaged controller for driving three vending-machine motors with sensor feedback and PC-based configuration.",
    technologies: ["Embedded controller", "USB serial", "Motor drivers", "Sensor inputs", "Desktop utility"],
    sourceFolder: "Vending Machine",
    tags: ["Vending Machine", "Motor Control", "USB", "Embedded"],
    specs: ["Three motor channels", "Sensor terminals", "USB configuration software"],
    challenges: ["Reliable dispense cycles", "Simple field wiring", "PC-device communication"],
    results: ["Completed the controller enclosure, wiring interface, software screen, and demonstration"],
    future: ["Add transaction APIs, stock sensing, fault logs, and cashless payment integration"],
    coverSource: "Vending Machine/VendinMachineSoftware.jpg",
    publish: true,
  }),
  project({
    slug: "fleet-tracking-platform",
    title: "Fleet Tracking and Vehicle Telemetry Platform",
    category: "Automotive Systems",
    industry: "Fleet operations",
    discipline: "GPS tracking and IoT software",
    purpose: "A web-based fleet platform for vehicle location, geofencing, route history, fuel, engine, and sensor status.",
    technologies: ["GPS", "Geofencing", "Web maps", "Vehicle telemetry", "Alerts"],
    sourceFiles: ["Fleet Tracking.mp4"],
    tags: ["Fleet Tracking", "GPS", "Geofencing", "Automotive IoT"],
    challenges: ["Reliable position updates", "Geofence event handling", "Operational visualization"],
    results: ["Recorded a functioning map-based fleet monitoring interface"],
    future: ["Add CAN integration, route optimization, and predictive maintenance"],
    videoUrl: "https://www.youtube.com/watch?v=pjLLVso4FRQ",
  }),
  project({
    slug: "line-following-robot",
    title: "Arduino Line-Following Robot",
    category: "Robotics",
    industry: "Educational robotics",
    discipline: "Sensor-based motion control",
    purpose: "A compact Arduino robot using infrared sensors and an AFMotor shield to follow a marked path.",
    technologies: ["Arduino", "IR sensors", "AFMotor Shield", "DC motors"],
    sourceFiles: ["Line following car using AFMotor Shield, IR Sensors & Arduino.mp4"],
    tags: ["Line Following", "Arduino", "IR Sensor", "Robot Car"],
    results: ["Demonstrated closed-loop path following on a floor course"],
    future: ["Add PID steering and speed adaptation for curves"],
  }),
  project({
    slug: "obstacle-avoiding-robot",
    title: "Obstacle-Avoiding Robot Car Variants",
    category: "Robotics",
    industry: "Educational robotics",
    discipline: "Autonomous mobile control",
    purpose: "Two robot-car implementations comparing AFMotor Shield and L298N motor-driver configurations for obstacle avoidance.",
    technologies: ["Arduino", "Ultrasonic sensing", "AFMotor Shield", "L298N", "DC motors"],
    sourceFiles: ["Obstacle Avoiding Car using AFMotor Shield.mp4", "Obstacle Avoiding Car using L298N motor module.mp4"],
    tags: ["Obstacle Avoidance", "Arduino", "L298N", "Robot Car"],
    challenges: ["Reactive steering", "Motor-driver differences", "Sensor placement"],
    results: ["Demonstrated autonomous motion with two hardware configurations"],
    future: ["Compare power efficiency, turning accuracy, and navigation behavior"],
  }),
  project({
    slug: "robotic-arm-prototype",
    title: "Robotic Arm Prototype",
    category: "Robotics",
    industry: "Educational robotics",
    discipline: "Manipulator design and control",
    purpose: "A multi-joint robotic arm demonstration focused on coordinated actuator movement.",
    technologies: ["Robotic arm", "Servo control", "Mechanism design"],
    sourceFiles: ["Robotic arm.mp4"],
    tags: ["Robotic Arm", "Servo", "Manipulator"],
    results: ["Recorded a working multi-axis manipulator prototype"],
    future: ["Document degrees of freedom, payload, control method, and kinematics"],
  }),
  project({
    slug: "self-balancing-robot",
    title: "Self-Balancing Two-Wheel Robot",
    category: "Robotics",
    industry: "Control systems education",
    discipline: "Dynamic control",
    purpose: "A two-wheel balancing platform demonstrating real-time stabilization.",
    technologies: ["IMU", "PID control", "DC motors", "Embedded control"],
    sourceFiles: ["selfbalancing robot.mp4"],
    tags: ["Self Balancing", "PID", "IMU", "Control Systems"],
    challenges: ["Fast feedback", "Controller tuning", "Mechanical center of gravity"],
    results: ["Demonstrated an operating self-balancing prototype"],
    future: ["Publish tuning curves, sensor filtering, and disturbance tests"],
  }),
  project({
    slug: "sewing-needle-detector",
    title: "Sewing Machine Needle Detection System",
    category: "Electronics",
    industry: "Textile manufacturing",
    discipline: "Industrial sensing and quality control",
    purpose: "A machine-mounted sensing prototype for detecting the sewing needle or needle position during operation.",
    technologies: ["Industrial sensor", "Machine integration", "Detection electronics"],
    sourceFiles: ["Sewing machine needle detector.mp4"],
    tags: ["Textile", "Industrial Sensor", "Quality Control"],
    confidence: "asset evidence - sensing method requires confirmation",
    results: ["Recorded the sensor installed and operating on a sewing machine"],
    future: ["Document sensor physics, detection latency, false positives, and machine interlock"],
  }),
  project({
    slug: "wifi-switch-and-bulb",
    title: "Wi-Fi Smart Switch and Bulb Controller",
    category: "IoT",
    industry: "Home and building automation",
    discipline: "Connected embedded products",
    purpose: "A connected switch and lamp controller for remote equipment operation.",
    technologies: ["Wi-Fi", "ESP8266", "Relay control", "IoT"],
    sourceFiles: ["Wifi Switch and Bulb.mp4"],
    tags: ["Smart Switch", "ESP8266", "Home Automation", "IoT"],
    results: ["Demonstrated packaged connected switching hardware"],
    future: ["Add secure provisioning, energy monitoring, and local automation rules"],
    repositories: ["https://github.com/Chathunka/ESP8266"],
  }),
];
